# Project: ProyectoFinal
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ColabMain.o Funciones_Colab.o gestion_de_productos_predefinidos.o
LINKOBJ  = ColabMain.o Funciones_Colab.o gestion_de_productos_predefinidos.o
LIBS     = -L"D:/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ProyectoFinal.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

ColabMain.o: ColabMain.cpp
	$(CPP) -c ColabMain.cpp -o ColabMain.o $(CXXFLAGS)

Funciones_Colab.o: Funciones_Colab.cpp
	$(CPP) -c Funciones_Colab.cpp -o Funciones_Colab.o $(CXXFLAGS)

gestion_de_productos_predefinidos.o: gestion_de_productos_predefinidos.cpp
	$(CPP) -c gestion_de_productos_predefinidos.cpp -o gestion_de_productos_predefinidos.o $(CXXFLAGS)
